insert  into service_area(id,area_name,created_by,created_date,post_code) values (1,'Aberdeen_AB',NULL,NULL,'AB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (2,'Aberdeenshire_AB',NULL,NULL,'AB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (3,'Kincardineshire_AB',NULL,NULL,'AB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (4,'Banffshire_AB',NULL,NULL,'AB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (5,'Hertfordshire_AL',NULL,NULL,'AL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (7,'Warwickshire_B',NULL,NULL,'B');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (8,'Worcestershire_B',NULL,NULL,'B');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (9,'Staffordshire_B',NULL,NULL,'B');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (10,'West Midlands_B',NULL,NULL,'B');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (12,'Somerset_BA',NULL,NULL,'BA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (13,'Wiltshire_BA',NULL,NULL,'BA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (15,'Lancashire_BB',NULL,NULL,'BB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (16,'West Yorkshire_BD',NULL,NULL,'BD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (17,'North Yorkshire_BD',NULL,NULL,'BD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (18,'Hampshire_BH',NULL,NULL,'BH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (19,'Dorset_BH',NULL,NULL,'BH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (20,'Lancashire_BL',NULL,NULL,'BL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (21,'Sussex_BN',NULL,NULL,'BN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (22,'Kent_BR',NULL,NULL,'BR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (23,'Gloucestershire_BS',NULL,NULL,'BS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (24,'Somerset_BS',NULL,NULL,'BS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (25,'County Antrim_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (26,'County Down_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (27,'County Londonderry_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (28,'County Armagh_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (29,'County Tyrone_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (30,'County Fermanagh_BT',NULL,NULL,'BT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (31,'Cumberland_CA',NULL,NULL,'CA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (32,'Westmorland_CA',NULL,NULL,'CA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (33,'Cumbria_CA',NULL,NULL,'CA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (35,'Essex_CB',NULL,NULL,'CB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (36,'Cambridgeshire_CB',NULL,NULL,'CB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (37,'Suffolk_CB',NULL,NULL,'CB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (38,'Glamorgan_CF',NULL,NULL,'CF');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (39,'Cheshire_CH',NULL,NULL,'CH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (41,'Flintshire_CH',NULL,NULL,'CH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (42,'Essex_CM',NULL,NULL,'CM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (43,'Hertfordshire_CM',NULL,NULL,'CM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (44,'Essex_CO',NULL,NULL,'CO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (45,'Suffolk_CO',NULL,NULL,'CO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (46,'Surrey_CR',NULL,NULL,'CR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (47,'Kent_CT',NULL,NULL,'CT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (48,'West Midlands_CV',NULL,NULL,'CV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (50,'Warwickshire_CV',NULL,NULL,'CV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (51,'Cheshire_CW',NULL,NULL,'CW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (52,'Kent_DA',NULL,NULL,'DA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (54,'Fife_DD',NULL,NULL,'DD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (55,'Angus_DD',NULL,NULL,'DD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (57,'Derbyshire_DE',NULL,NULL,'DE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (58,'Staffordshire_DE',NULL,NULL,'DE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (59,'Dumfries and Galloway_DG',NULL,NULL,'DG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (60,'Dumfriesshire_DG',NULL,NULL,'DG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (61,'Kirkcudbrightshire_DG',NULL,NULL,'DG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (62,'Wigtownshire_DG',NULL,NULL,'DG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (63,'County Durham_DH',NULL,NULL,'DH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (64,'County Durham_DL',NULL,NULL,'DL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (65,'North Yorkshire_DL',NULL,NULL,'DL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (66,'South Yorkshire_DN',NULL,NULL,'DN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (67,'East Yorkshire_DN',NULL,NULL,'DN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (68,'Lincolnshire_DN',NULL,NULL,'DN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (69,'Nottinghamshire_DN',NULL,NULL,'DN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (70,'Dorset_DT',NULL,NULL,'DT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (71,'Worcestershire_DY',NULL,NULL,'DY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (72,'Staffordshire_DY',NULL,NULL,'DY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (73,'London_E',NULL,NULL,'E');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (74,'London_EW',NULL,NULL,'EW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (75,'City of London_EC',NULL,NULL,'EC');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (76,'City of London_ECA',NULL,NULL,'ECA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (77,'City of London_ECM',NULL,NULL,'ECM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (78,'City of London_ECN',NULL,NULL,'ECN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (79,'City of London_ECR',NULL,NULL,'ECR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (80,'City of London_ECV',NULL,NULL,'ECV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (81,'City of London_ECY',NULL,NULL,'ECY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (82,'City of London_ECP',NULL,NULL,'ECP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (83,'Edinburgh_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (84,'Midlothian_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (87,'East Lothian_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (88,'Peeblesshire_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (89,'Tweeddale_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (90,'West Lothian_EH',NULL,NULL,'EH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (91,'Middlesex_EN',NULL,NULL,'EN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (92,'Hertfordshire_EN',NULL,NULL,'EN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (93,'Essex_EN',NULL,NULL,'EN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (94,'Devon_EX',NULL,NULL,'EX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (95,'Cornwall_EX',NULL,NULL,'EX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (96,'Stirlingshire_FK',NULL,NULL,'FK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (97,'Clackmannanshire_FK',NULL,NULL,'FK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (98,'Perthshire_FK',NULL,NULL,'FK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (99,'Stirling_FK',NULL,NULL,'FK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (100,'Lancashire_FY',NULL,NULL,'FY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (101,'Lanarkshire_G',NULL,NULL,'G');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (103,'Dunbartonshire_G',NULL,NULL,'G');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (105,'Gloucestershire_GL',NULL,NULL,'GL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (106,'Surrey_GU',NULL,NULL,'GU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (108,'Hampshire_GU',NULL,NULL,'GU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (109,'Sussex_GU',NULL,NULL,'GU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (110,'Berkshire_GU',NULL,NULL,'GU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (111,'Middlesex_HA',NULL,NULL,'HA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (112,'West Yorkshire_HD',NULL,NULL,'HD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (113,'North Yorkshire_HG',NULL,NULL,'HG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (114,'Hertfordshire_HP',NULL,NULL,'HP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (115,'Buckinghamshire_HP',NULL,NULL,'HP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (116,'Herefordshire_HR',NULL,NULL,'HR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (117,'County of Herefordshire_HR',NULL,NULL,'HR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (118,'Outer Hebrides_HS',NULL,NULL,'HS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (119,'Ross-shire_HS',NULL,NULL,'HS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (120,'Inverness-shire_HS',NULL,NULL,'HS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (121,'East Yorkshire_HU',NULL,NULL,'HU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (122,'West Yorkshire_HX',NULL,NULL,'HX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (123,'Essex_IG',NULL,NULL,'IG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (124,'Suffolk_IP',NULL,NULL,'IP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (125,'Norfolk_IP',NULL,NULL,'IP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (126,'Inverness-shire_IV',NULL,NULL,'IV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (127,'Ross-shire_IV',NULL,NULL,'IV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (128,'Highland_IV',NULL,NULL,'IV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (129,'Sutherland_IV',NULL,NULL,'IV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (130,'Morayshire_IV',NULL,NULL,'IV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (131,'Ayrshire_KA',NULL,NULL,'KA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (132,'Buteshire_KA',NULL,NULL,'KA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (133,'South Ayrshire_KA',NULL,NULL,'KA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (134,'Surrey_KT',NULL,NULL,'KT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (135,'Caithness_KW',NULL,NULL,'KW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (136,'Sutherland_KW',NULL,NULL,'KW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (137,'Orkney_KW',NULL,NULL,'KW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (138,'Fife_KY',NULL,NULL,'KY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (139,'Kinross-Shire_KY',NULL,NULL,'KY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (140,'Lancashire_L',NULL,NULL,'L');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (141,'Lancashire_LA',NULL,NULL,'LA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (142,'Cumbria_LA',NULL,NULL,'LA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (143,'Cumberland_LA',NULL,NULL,'LA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (144,'Westmorland_LA',NULL,NULL,'LA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (145,'Radnorshire_LD',NULL,NULL,'LD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (146,'Brecknockshire_LD',NULL,NULL,'LD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (148,'Leicestershire_LE',NULL,NULL,'LE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (149,'Rutland_LE',NULL,NULL,'LE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (151,'Denbighshire_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (152,'Clwyd_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (153,'Flintshire_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (154,'Merioneth_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (155,'Caernarfonshire_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (156,'Gwynedd_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (157,'Anglesey_LL',NULL,NULL,'LL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (159,'Lincolnshire_LN',NULL,NULL,'LN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (160,'West Yorkshire_LS',NULL,NULL,'LS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (161,'North Yorkshire_LS',NULL,NULL,'LS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (162,'Bedfordshire_LU',NULL,NULL,'LU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (163,'Lancashire_M',NULL,NULL,'M');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (164,'Cheshire_M',NULL,NULL,'M');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (165,'Kent_ME',NULL,NULL,'ME');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (167,'Buckinghamshire_MK',NULL,NULL,'MK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (168,'Bedfordshire_MK',NULL,NULL,'MK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (169,'Lanarkshire_ML',NULL,NULL,'ML');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (170,'South Lanarkshire_ML',NULL,NULL,'ML');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (171,'London_N',NULL,NULL,'N');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (172,'Northumberland_NE',NULL,NULL,'NE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (173,'County Durham_NE',NULL,NULL,'NE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (175,'Nottinghamshire_NG',NULL,NULL,'NG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (176,'Lincolnshire_NG',NULL,NULL,'NG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (178,'Northamptonshire_NN',NULL,NULL,'NN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (180,'Monmouthshire_NP',NULL,NULL,'NP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (181,'Brecknockshire_NP',NULL,NULL,'NP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (182,'Norfolk_NR',NULL,NULL,'NR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (183,'Suffolk_NR',NULL,NULL,'NR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (184,'London_NW',NULL,NULL,'NW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (185,'Lancashire_OL',NULL,NULL,'OL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (187,'Berkshire_OX',NULL,NULL,'OX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (188,'Oxfordshire_OX',NULL,NULL,'OX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (190,'Ayrshire_PA',NULL,NULL,'PA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (191,'Buteshire_PA',NULL,NULL,'PA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (192,'Argyllshire_PA',NULL,NULL,'PA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (193,'Renfrewshire_PA',NULL,NULL,'PA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (194,'Northamptonshire_PE',NULL,NULL,'PE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (195,'Lincolnshire_PE',NULL,NULL,'PE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (197,'Cambridgeshire_PE',NULL,NULL,'PE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (198,'Norfolk_PE',NULL,NULL,'PE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (199,'Perth and Kinross_PH',NULL,NULL,'PH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (200,'Perthshire_PH',NULL,NULL,'PH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (201,'Inverness-shire_PH',NULL,NULL,'PH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (202,'Highland_PH',NULL,NULL,'PH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (203,'Argyllshire_PH',NULL,NULL,'PH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (204,'Devon_PL',NULL,NULL,'PL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (205,'Cornwall_PL',NULL,NULL,'PL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (206,'Hampshire_PO',NULL,NULL,'PO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (207,'Sussex_PO',NULL,NULL,'PO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (208,'Monmouthshire_PO',NULL,NULL,'PO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (209,'Isle of Wight_PO',NULL,NULL,'PO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (210,'Lancashire_PR',NULL,NULL,'PR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (211,'Berkshire_RG',NULL,NULL,'RG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (212,'Hampshire_RG',NULL,NULL,'RG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (213,'Oxfordshire_RG',NULL,NULL,'RG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (214,'Surrey_RH',NULL,NULL,'RH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (215,'Sussex_RH',NULL,NULL,'RH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (216,'Essex_RM',NULL,NULL,'RM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (217,'South Yorkshire_S',NULL,NULL,'S');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (218,'Derbyshire_S',NULL,NULL,'S');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (219,'Nottinghamshire_S',NULL,NULL,'S');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (220,'Swansea_SA',NULL,NULL,'SA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (221,'Glamorgan_SA',NULL,NULL,'SA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (223,'Carmarthenshire_SA',NULL,NULL,'SA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (226,'Ceredigion_SA',NULL,NULL,'SA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (227,'Pembrokeshire_SA',NULL,NULL,'SA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (228,'London_SE',NULL,NULL,'SE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (230,'Hertfordshire_SG',NULL,NULL,'SG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (231,'Bedfordshire_SG',NULL,NULL,'SG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (232,'Cheshire_SK',NULL,NULL,'SK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (233,'Derbyshire_SK',NULL,NULL,'SK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (234,'Buckinghamshire_SL',NULL,NULL,'SL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (235,'Berkshire_SL',NULL,NULL,'SL');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (236,'Surrey_SM',NULL,NULL,'SM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (237,'Wiltshire_SN',NULL,NULL,'SN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (238,'Berkshire_SN',NULL,NULL,'SN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (239,'Hampshire_SO',NULL,NULL,'SO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (240,'Wiltshire_SP',NULL,NULL,'SP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (241,'Hampshire_SP',NULL,NULL,'SP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (242,'Dorset_SP',NULL,NULL,'SP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (243,'County Durham_SR',NULL,NULL,'SR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (244,'Essex_SS',NULL,NULL,'SS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (246,'Staffordshire_ST',NULL,NULL,'ST');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (247,'London_SW',NULL,NULL,'SW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (248,'London_SWA',NULL,NULL,'SWA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (249,'London_SWE',NULL,NULL,'SWE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (250,'London_SWH',NULL,NULL,'SWH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (251,'London_SWP',NULL,NULL,'SWP');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (252,'London_SWV',NULL,NULL,'SWV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (253,'London_SWW',NULL,NULL,'SWW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (254,'London_SWX',NULL,NULL,'SWX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (255,'London_SWY',NULL,NULL,'SWY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (256,'Shropshire_SY',NULL,NULL,'SY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (257,'Cheshire_SY',NULL,NULL,'SY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (258,'Powys_SY',NULL,NULL,'SY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (259,'Montgomeryshire_SY',NULL,NULL,'SY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (260,'Ceredigion_SY',NULL,NULL,'SY');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (261,'Somerset_TA',NULL,NULL,'TA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (262,'Selkirkshire_TD',NULL,NULL,'TD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (263,'Berwickshire_TD',NULL,NULL,'TD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (264,'Northumberland_TD',NULL,NULL,'TD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (265,'Roxburghshire_TD',NULL,NULL,'TD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (266,'Scottish Borders_TD',NULL,NULL,'TD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (267,'Shropshire_TF',NULL,NULL,'TF');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (268,'Kent_TN',NULL,NULL,'TN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (269,'Sussex_TN',NULL,NULL,'TN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (270,'East Sussex_TN',NULL,NULL,'TN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (271,'Devon_TQ',NULL,NULL,'TQ');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (272,'Cornwall_TR',NULL,NULL,'TR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (273,'Isles of Scilly_TR',NULL,NULL,'TR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (274,'North Yorkshire_TS',NULL,NULL,'TS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (275,'County Durham_TS',NULL,NULL,'TS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (276,'Middlesex_TW',NULL,NULL,'TW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (277,'Surrey_TW',NULL,NULL,'TW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (278,'Middlesex_UB',NULL,NULL,'UB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (279,'London_W',NULL,NULL,'W');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (280,'London_WB',NULL,NULL,'WB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (281,'London_WC',NULL,NULL,'WC');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (282,'London_WD',NULL,NULL,'WD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (283,'London_WF',NULL,NULL,'WF');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (284,'London_WG',NULL,NULL,'WG');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (285,'London_WH',NULL,NULL,'WH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (286,'London_WJ',NULL,NULL,'WJ');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (287,'London_WK',NULL,NULL,'WK');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (288,'London_WM',NULL,NULL,'WM');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (289,'London_WS',NULL,NULL,'WS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (290,'London_WT',NULL,NULL,'WT');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (291,'London_WU',NULL,NULL,'WU');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (292,'London_WW',NULL,NULL,'WW');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (293,'Lancashire_WA',NULL,NULL,'WA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (294,'Merseyside_WA',NULL,NULL,'WA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (295,'Cheshire_WA',NULL,NULL,'WA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (296,'London_WCA',NULL,NULL,'WCA');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (297,'London_WCB',NULL,NULL,'WCB');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (298,'London_WCE',NULL,NULL,'WCE');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (299,'London_WCH',NULL,NULL,'WCH');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (300,'London_WCN',NULL,NULL,'WCN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (301,'London_WCR',NULL,NULL,'WCR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (302,'London_WCV',NULL,NULL,'WCV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (303,'London_WCX',NULL,NULL,'WCX');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (304,'Hertfordshire_WD',NULL,NULL,'WD');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (305,'West Yorkshire_WF',NULL,NULL,'WF');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (306,'Lancashire_WN',NULL,NULL,'WN');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (308,'Worcestershire_WR',NULL,NULL,'WR');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (309,'Staffordshire_WS',NULL,NULL,'WS');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (310,'Staffordshire_WV',NULL,NULL,'WV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (311,'Shropshire_WV',NULL,NULL,'WV');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (312,'North Yorkshire_YO',NULL,NULL,'YO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (313,'East Yorkshire_YO',NULL,NULL,'YO');
insert  into service_area(id,area_name,created_by,created_date,post_code) values (314,'Shetland_ZE',NULL,NULL,'ZE');